### ISSUE TITLE
Missing 'clusterid' in context

### ISSUE THREAD

**Issue by srueg** [awslabs/aws-servicebroker#67]
**Describe the bug**
When I create a ServiceInstance (e.g. S3) the AWS service broker panics:
```
I1113 12:12:55.900058       1 awsbroker.go:239] Client OSB API Version: "2.13"
I1113 12:12:55.900164       1 apisurface.go:89] Received ProvisionRequest for instanceID "c58bb5e8-1318-4dab-b02d-ec551158f200"
I1113 12:12:55.900194       1 api.go:54] request={InstanceID:c58bb5e8-1318-4dab-b02d-ec551158f200 AcceptsIncomplete:true ServiceID:0d7d708a-006e-5d0b-a151-264c90a1599c PlanID:33d9dd5d-fc6d-5a09-9e25-485cc5e05eb4 OrganizationGUID:63ac6aa8-e72e-11e8-b440-028d5585b360 SpaceGUID:63ac6aa8-e72e-11e8-b440-028d5585b360 Parameters:map[GlacierLifeCycleTransitionInDays:0 LifeCyclePrefix:Archive LoggingPrefix:Archive BucketAccessControl:Private BucketName:Auto EnableGlacierLifeCycle:False EnableLogging:True EnableVersioning:False] Context:map[namespace:srueg-test platform:kubernetes] OriginatingIdentity:0xc00049c600}
2018/11/13 12:12:55 http: panic serving 10.1.2.59:54002: interface conversion: interface {} is nil, not string
goroutine 5815 [running]:
net/http.(*conn).serve.func1(0xc00056a320)
	/usr/local/go/src/net/http/server.go:1746 +0xd0
panic(0xc38180, 0xc000681c20)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/awslabs/aws-servicebroker/pkg/broker.getCluster(0xc000681b90, 0xd4bab4, 0xb)
	/go/src/github.com/awslabs/aws-servicebroker/pkg/broker/util.go:296 +0x22d
github.com/awslabs/aws-servicebroker/pkg/broker.(*AwsBroker).Provision(0xc000166000, 0xc000174380, 0xc00049c620, 0xc0005c5bc0, 0x1, 0x1)
	/go/src/github.com/awslabs/aws-servicebroker/pkg/broker/api.go:61 +0xee
github.com/awslabs/aws-servicebroker/vendor/github.com/pmorie/osb-broker-lib/pkg/rest.(*APISurface).ProvisionHandler(0xc000444140, 0xe349c0, 0xc00054a700, 0xc000264d00)
	/go/src/github.com/awslabs/aws-servicebroker/vendor/github.com/pmorie/osb-broker-lib/pkg/rest/apisurface.go:96 +0x1d1
github.com/awslabs/aws-servicebroker/vendor/github.com/pmorie/osb-broker-lib/pkg/rest.(*APISurface).ProvisionHandler-fm(0xe349c0, 0xc00054a700, 0xc000264d00)
	/go/src/github.com/awslabs/aws-servicebroker/vendor/github.com/jaymccon/osb-broker-lib/pkg/server/server.go:82 +0x48
net/http.HandlerFunc.ServeHTTP(0xc0002262b0, 0xe349c0, 0xc00054a700, 0xc000264d00)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/awslabs/aws-servicebroker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0004002a0, 0xe349c0, 0xc00054a700, 0xc000264d00)
	/go/src/github.com/awslabs/aws-servicebroker/vendor/github.com/gorilla/mux/mux.go:162 +0xf1
net/http.serverHandler.ServeHTTP(0xc00015a270, 0xe349c0, 0xc00054a700, 0xc000264b00)
	/usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc00056a320, 0xe35140, 0xc0000a91c0)
	/usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5
```
The error seems to be, that the context which is delivered with the provisioning request doesn't contain the `clusterid` filed: https://github.com/awslabs/aws-servicebroker/blob/release-v1.0.0-beta.3/pkg/broker/util.go#L273

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
The ServiceInstance gets provisioned successfully.

**Environment (please complete the following information):**
 - Application Platform: OpenShift Container Platform v3.9
 - Application Platform Version: k8s 1.9, OpenShift v3.9
 - Broker Version: release-v1.0.0-beta.3

**Additional context**
It's a fresh installation and provisioning never worked.

**Comment by srueg** [comment]
Is this service broker supported on OpenShift v3.9 (Kubernetes 1.9)?

**Comment by jaymccon** [comment]
At present what is supported is not well defined. It's generally more about the version of service catalog, than the kube/openshift version. c6de56d should address this (although I have not tested against openshift 3.9 to see if there are any other issues)

**Comment by srueg** [comment]
Thanks, that might solve my problem. Was this pushed to Docker hub? Or how is the release process?

**Comment by srueg** [comment]
Never mind, I compiled it myself. Thanks for your help, it actually solved the problem. I ran into the next one but I can go on from here. :+1:
